; This file was automatically generated by ScriptHubImporter.py
this.BrivUnnaturalHasteHandler.sprintStacks := New GameObjectStructure(this.BrivUnnaturalHasteHandler,"Int", [0x48])
this.BrivUnnaturalHasteHandler.sprintStacks.stackCount := New GameObjectStructure(this.BrivUnnaturalHasteHandler.sprintStacks,"Double", [0xb0])
this.BrivUnnaturalHasteHandler.areasSkipped := New GameObjectStructure(this.BrivUnnaturalHasteHandler,"Int", [0x70])
this.BrivUnnaturalHasteHandler.areaSkipChance := New GameObjectStructure(this.BrivUnnaturalHasteHandler,"Float", [0x78])
this.BrivUnnaturalHasteHandler.areaSkipAmount := New GameObjectStructure(this.BrivUnnaturalHasteHandler,"Int", [0x7c])
this.BrivUnnaturalHasteHandler.alwaysSkipOneLess := New GameObjectStructure(this.BrivUnnaturalHasteHandler,"Char", [0x80])

if (!IsObject(IC_ActiveEffectKeyHandler_Class.NewHandlerObject))
	MsgBox % "Please update importer and/or imports to match this script."