; This file was automatically generated by ScriptHubImporter.py
BuildBrivUnnaturalHasteHandler()
{
	#include %A_LineFile%\..\IC_BrivUnnaturalHasteHandler64_Import.ahk
}
BuildEllywickCallOfTheFeywildHandler()
{
	#include %A_LineFile%\..\IC_EllywickCallOfTheFeywildHandler64_Import.ahk
}
BuildHavilarImpHandler()
{
	#include %A_LineFile%\..\IC_HavilarImpHandler64_Import.ahk
}
BuildHewMaanTeamworkHandler()
{
	#include %A_LineFile%\..\IC_HewMaanTeamworkHandler64_Import.ahk
}
BuildJimMagicalMysteryTourHandler()
{
	#include %A_LineFile%\..\IC_JimMagicalMysteryTourHandler64_Import.ahk
}
BuildNerdWagonHandler()
{
	#include %A_LineFile%\..\IC_NerdWagonHandler64_Import.ahk
}
BuildNordomModronCoreToolboxHandler()
{
	#include %A_LineFile%\..\IC_NordomModronCoreToolboxHandler64_Import.ahk
}
BuildNrakkUltimateAttackHandler()
{
	#include %A_LineFile%\..\IC_NrakkUltimateAttackHandler64_Import.ahk
}
BuildOminContractualObligationsHandler()
{
	#include %A_LineFile%\..\IC_OminContractualObligationsHandler64_Import.ahk
}
BuildSpurtWaspirationHandlerV2()
{
	#include %A_LineFile%\..\IC_SpurtWaspirationHandlerV264_Import.ahk
}
BuildThelloraPlateausOfUnicornRunHandler()
{
	#include %A_LineFile%\..\IC_ThelloraPlateausOfUnicornRunHandler64_Import.ahk
}
BuildTimeScaleWhenNotAttackedHandler()
{
	#include %A_LineFile%\..\IC_TimeScaleWhenNotAttackedHandler64_Import.ahk
}
