; This file was automatically generated by ScriptHubImporter.py
this.HewMaanTeamworkHandler.hewmaan := New GameObjectStructure(this.HewMaanTeamworkHandler,"Int", [0x48])
this.HewMaanTeamworkHandler.hewmaan.ultimateAttack := New GameObjectStructure(this.HewMaanTeamworkHandler.hewmaan,"Int", [0x2a8])
this.HewMaanTeamworkHandler.hewmaan.ultimateAttack.ID := New GameObjectStructure(this.HewMaanTeamworkHandler.hewmaan.ultimateAttack,"Int", [0x10])
this.HewMaanTeamworkHandler.hewmaan.ultimateAttack.internalCooldownTimer := New GameObjectStructure(this.HewMaanTeamworkHandler.hewmaan.ultimateAttack,"Float", [0xb8])
