; This file was automatically generated by ScriptHubImporter.py
this.HavilarImpHandler.activeImps := New GameObjectStructure(this.HavilarImpHandler,"HashSet", [0x80])
this.HavilarImpHandler.activeImps._CollectionKeyType := "System.Int32"
this.HavilarImpHandler.currentOtherImpIndex := New GameObjectStructure(this.HavilarImpHandler,"Int", [0x1c0])
this.HavilarImpHandler.summonImpUltimate := New GameObjectStructure(this.HavilarImpHandler,"Int", [0xb0])
this.HavilarImpHandler.summonImpUltimate.internalCooldownTimer := New GameObjectStructure(this.HavilarImpHandler.summonImpUltimate,"Float", [0xb8])
this.HavilarImpHandler.sacrificeImpUltimate := New GameObjectStructure(this.HavilarImpHandler,"Int", [0xb8])
this.HavilarImpHandler.sacrificeImpUltimate.internalCooldownTimer := New GameObjectStructure(this.HavilarImpHandler.sacrificeImpUltimate,"Float", [0xb8])
