; This file was automatically generated by ScriptHubImporter.py
this.NordomModronCoreToolboxHandler.controller := New GameObjectStructure(this.NordomModronCoreToolboxHandler,"Int", [0x10])
this.NordomModronCoreToolboxHandler.controller.GameInstance_k__BackingField := New GameObjectStructure(this.NordomModronCoreToolboxHandler.controller,"Int", [0x10])
this.NordomModronCoreToolboxHandler.controller.GameInstance_k__BackingField.StatHandler := New GameObjectStructure(this.NordomModronCoreToolboxHandler.controller.GameInstance_k__BackingField,"Int", [0x50])
this.NordomModronCoreToolboxHandler.controller.GameInstance_k__BackingField.StatHandler.NordomAwardedEXP := New GameObjectStructure(this.NordomModronCoreToolboxHandler.controller.GameInstance_k__BackingField.StatHandler,"Int", [0x284])
this.NordomModronCoreToolboxHandler.controller.GameInstance_k__BackingField.StatHandler.NordomPendingEXP := New GameObjectStructure(this.NordomModronCoreToolboxHandler.controller.GameInstance_k__BackingField.StatHandler,"Float", [0x288])
