; This file was automatically generated by ScriptHubImporter.py
this.OminContractualObligationsHandler.obligationsFufilled := New GameObjectStructure(this.OminContractualObligationsHandler,"Int", [0xb8])
