; This file was automatically generated by ScriptHubImporter.py
this.TimeScaleWhenNotAttackedHandler.scaleActive := New GameObjectStructure(this.TimeScaleWhenNotAttackedHandler,"Char", [0x148])
this.TimeScaleWhenNotAttackedHandler.effectTime := New GameObjectStructure(this.TimeScaleWhenNotAttackedHandler,"Double", [0x150])
