; This file was automatically generated by ScriptHubImporter.py
this.BuffDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0x20])
this.BuffDefines._CollectionValType := "CrusadersGame.Defs.BuffDef"
this.AreaDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0x18])
this.AreaDefines._CollectionValType := "CrusadersGame.Defs.AreaDef"
this.UpgradeDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0xf8])
this.UpgradeDefines._CollectionValType := "CrusadersGame.Defs.UpgradeDef"
this.AdventureDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0x170])
this.AdventureDefines._CollectionValType := "CrusadersGame.Defs.AdventureDef"
this.ChestTypeDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0x48])
this.ChestTypeDefines._CollectionValType := "CrusadersGame.Defs.ChestTypeDef"
this.ChestTypeDefines.ID := New GameObjectStructure(this.ChestTypeDefines,"Int", [0x10])
this.ChestTypeDefines.NamePlural := New GameObjectStructure(this.ChestTypeDefines,"UTF-16", [0x20])
this.ChestTypeDefines.Name := New GameObjectStructure(this.ChestTypeDefines,"UTF-16", [0x18])
