; This file was automatically generated by ScriptHubImporter.py
this.BuffDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0x20])
this.AreaDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0x18])
this.UpgradeDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0xf8])
this.AdventureDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0x170])
this.ChestTypeDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0x48])
this.ChestTypeDefines.ID := New GameObjectStructure(this.ChestTypeDefines,"Int", [0x10])
this.ChestTypeDefines.NamePlural := New GameObjectStructure(this.ChestTypeDefines,"UTF-16", [0x20])
this.ChestTypeDefines.Name := New GameObjectStructure(this.ChestTypeDefines,"UTF-16", [0x18])
