; This file was automatically generated by ScriptHubImporter.py
this.UserID := New GameObjectStructure(this.CrusadersGame.GameSettings,"Int", [this.StaticOffset + 0x24])
this.Hash := New GameObjectStructure(this.CrusadersGame.GameSettings,"UTF-16", [this.StaticOffset + 0x2c])
this.Platform := New GameObjectStructure(this.CrusadersGame.GameSettings,"Int", [this.StaticOffset + 0x4c])
this.MobileClientVersion := New GameObjectStructure(this.CrusadersGame.GameSettings,"Int", [this.StaticOffset + 0x54])
this.VersionPostFix := New GameObjectStructure(this.CrusadersGame.GameSettings,"UTF-16", [this.StaticOffset + 0x58])
this._instance := New GameObjectStructure(this.CrusadersGame.GameSettings,"Int", [this.StaticOffset + 0x0])
this._instance.instanceID := New GameObjectStructure(this._instance,"Int", [0x10])
