; This file was automatically generated by ScriptHubImporter.py
this.nerd0 := New GameObjectStructure(this.CrusadersGame.Effects.NerdWagonHandler,"Int", [0x40])
this.nerd0.type := New GameObjectStructure(this.nerd0,"Int", [0x20])
this.nerd1 := New GameObjectStructure(this.CrusadersGame.Effects.NerdWagonHandler,"Int", [0x48])
this.nerd1.type := New GameObjectStructure(this.nerd1,"Int", [0x20])
this.nerd2 := New GameObjectStructure(this.CrusadersGame.Effects.NerdWagonHandler,"Int", [0x50])
this.nerd2.type := New GameObjectStructure(this.nerd2,"Int", [0x20])
