; This file was automatically generated by ScriptHubImporter.py
this.nerd0 := New GameObjectStructure(this.CrusadersGame.Effects.NerdWagonHandler,"Int", [0x20])
this.nerd1 := New GameObjectStructure(this.CrusadersGame.Effects.NerdWagonHandler,"Int", [0x24])
this.nerd2 := New GameObjectStructure(this.CrusadersGame.Effects.NerdWagonHandler,"Int", [0x28])
