; This file was automatically generated by ScriptHubImporter.py
this.inGameNumSecondsToProcess := New GameObjectStructure(this.OfflineProgressHandlerOLD,"Int", [0xec])
this.monstersSpawnedThisArea := New GameObjectStructure(this.OfflineProgressHandlerOLD,"Int", [0xd8])
this.modronSave := New GameObjectStructure(this.OfflineProgressHandlerOLD,"Int", [0x40])
this.modronSave.ExpTotal := New GameObjectStructure(this.modronSave,"Int", [0x50])
this.modronSave.targetArea := New GameObjectStructure(this.modronSave,"Int", [0x54])
this.finishedOfflineProgressType := New GameObjectStructure(this.OfflineProgressHandlerOLD,"Int", [0x144])
