; This file was automatically generated by ScriptHubImporter.py
this.numContractsFufilled := New GameObjectStructure(this.CrusadersGame.Effects.OminContractualObligationsHandler,"Int", [0x70])
this.secondsOnGoldFind := New GameObjectStructure(this.CrusadersGame.Effects.OminContractualObligationsHandler,"Float", [0x94])
this.effectKey := New GameObjectStructure(this.CrusadersGame.Effects.OminContractualObligationsHandler,"Int", [0x30])
this.effectKey.parentEffectKeyHandler := New GameObjectStructure(this.effectKey,"Int", [0x10])
this.effectKey.parentEffectKeyHandler.parent := New GameObjectStructure(this.effectKey.parentEffectKeyHandler,"Int", [0x10])
this.effectKey.parentEffectKeyHandler.parent.def := New GameObjectStructure(this.effectKey.parentEffectKeyHandler.parent,"Int", [0x10])
this.effectKey.parentEffectKeyHandler.parent.def.ID := New GameObjectStructure(this.effectKey.parentEffectKeyHandler.parent.def,"Int", [0x10])
this.effectKey.parentEffectKeyHandler.parent.source := New GameObjectStructure(this.effectKey.parentEffectKeyHandler.parent,"Int", [0x18])
