; This file was automatically generated by ScriptHubImporter.py
this.scaleActive := New GameObjectStructure(this.TimeScaleWhenNotAttackedHandler,"Char", [0x108])
this.effectTime := New GameObjectStructure(this.TimeScaleWhenNotAttackedHandler,"Double", [0x110])
this.effectKey := New GameObjectStructure(this.TimeScaleWhenNotAttackedHandler,"Int", [0x28])
this.effectKey.parentEffectKeyHandler := New GameObjectStructure(this.effectKey,"Int", [0x10])
this.effectKey.parentEffectKeyHandler.parent := New GameObjectStructure(this.effectKey.parentEffectKeyHandler,"Int", [0x10])
this.effectKey.parentEffectKeyHandler.parent.def := New GameObjectStructure(this.effectKey.parentEffectKeyHandler.parent,"Int", [0x10])
this.effectKey.parentEffectKeyHandler.parent.def.ID := New GameObjectStructure(this.effectKey.parentEffectKeyHandler.parent.def,"Int", [0x10])
this.effectKey.parentEffectKeyHandler.parent.source := New GameObjectStructure(this.effectKey.parentEffectKeyHandler.parent,"Int", [0x18])
