; This file was automatically generated by ScriptHubImporter.py
#include %A_LineFile%\..\IC_BrivUnnaturalHasteHandler64_Import.ahk
#include %A_LineFile%\..\IC_HavilarImpHandler64_Import.ahk
#include %A_LineFile%\..\IC_HewMaanTeamworkHandler64_Import.ahk
#include %A_LineFile%\..\IC_JimMagicalMysteryTourHandler64_Import.ahk
#include %A_LineFile%\..\IC_NerdWagonHandler64_Import.ahk
#include %A_LineFile%\..\IC_NordomModronCoreToolboxHandler64_Import.ahk
#include %A_LineFile%\..\IC_NrakkUltimateAttackHandler64_Import.ahk
#include %A_LineFile%\..\IC_OminContractualObligationsHandler64_Import.ahk
#include %A_LineFile%\..\IC_SpurtWaspirationHandlerV264_Import.ahk
#include %A_LineFile%\..\IC_ThelloraPlateausOfUnicornRunHandler64_Import.ahk
#include %A_LineFile%\..\IC_TimeScaleWhenNotAttackedHandler64_Import.ahk
