; This file was automatically generated by ScriptHubImporter.py
this.HewMaanTeamworkHandler.hewmaan := New GameObjectStructure(this.HewMaanTeamworkHandler,"Int", [0x38])
this.HewMaanTeamworkHandler.hewmaan.ultimateAttack := New GameObjectStructure(this.HewMaanTeamworkHandler.hewmaan,"Int", [0x278])
this.HewMaanTeamworkHandler.hewmaan.ultimateAttack.ID := New GameObjectStructure(this.HewMaanTeamworkHandler.hewmaan.ultimateAttack,"Int", [0x10])
this.HewMaanTeamworkHandler.hewmaan.ultimateAttack.CooldownTimer := New GameObjectStructure(this.HewMaanTeamworkHandler.hewmaan.ultimateAttack,"Float", [0xb0])
