; This file was automatically generated by ScriptHubImporter.py
this.HewMaanTeamworkHandler.hewmaan := New GameObjectStructure(this.HewMaanTeamworkHandler,"Int", [0x1c])
this.HewMaanTeamworkHandler.hewmaan.ultimateAttack := New GameObjectStructure(this.HewMaanTeamworkHandler.hewmaan,"Int", [0x14c])
this.HewMaanTeamworkHandler.hewmaan.ultimateAttack.ID := New GameObjectStructure(this.HewMaanTeamworkHandler.hewmaan.ultimateAttack,"Int", [0x8])
this.HewMaanTeamworkHandler.hewmaan.ultimateAttack.CooldownTimer := New GameObjectStructure(this.HewMaanTeamworkHandler.hewmaan.ultimateAttack,"Float", [0x78])
