; This file was automatically generated by ScriptHubImporter.py
this.NerdWagonHandler.nerd0 := New GameObjectStructure(this.NerdWagonHandler,"Int", [0x20])
this.NerdWagonHandler.nerd0.type := New GameObjectStructure(this.NerdWagonHandler.nerd0,"Int", [0x10])
this.NerdWagonHandler.nerd1 := New GameObjectStructure(this.NerdWagonHandler,"Int", [0x24])
this.NerdWagonHandler.nerd1.type := New GameObjectStructure(this.NerdWagonHandler.nerd1,"Int", [0x10])
this.NerdWagonHandler.nerd2 := New GameObjectStructure(this.NerdWagonHandler,"Int", [0x28])
this.NerdWagonHandler.nerd2.type := New GameObjectStructure(this.NerdWagonHandler.nerd2,"Int", [0x10])
