; This file was automatically generated by ScriptHubImporter.py
this.OminContractualObligationsHandler.obligationsFufilled := New GameObjectStructure(this.OminContractualObligationsHandler,"Int", [0xb0])
this.OminContractualObligationsHandler.effectKey := New GameObjectStructure(this.OminContractualObligationsHandler,"Int", [0x40])
this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler := New GameObjectStructure(this.OminContractualObligationsHandler.effectKey,"Int", [0x10])
this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent := New GameObjectStructure(this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler,"Int", [0x10])
this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent.def := New GameObjectStructure(this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent,"Int", [0x10])
this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent.def.ID := New GameObjectStructure(this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent.def,"Int", [0x10])
this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent.source := New GameObjectStructure(this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent,"Int", [0x18])
