; This file was automatically generated by ScriptHubImporter.py
this.OminContractualObligationsHandler.numContractsFufilled := New GameObjectStructure(this.OminContractualObligationsHandler,"Int", [0x70])
this.OminContractualObligationsHandler.secondsOnGoldFind := New GameObjectStructure(this.OminContractualObligationsHandler,"Float", [0x94])
this.OminContractualObligationsHandler.effectKey := New GameObjectStructure(this.OminContractualObligationsHandler,"Int", [0x30])
this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler := New GameObjectStructure(this.OminContractualObligationsHandler.effectKey.,"Int", [0x10])
this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent := New GameObjectStructure(this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.,"Int", [0x10])
this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent.def := New GameObjectStructure(this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent.,"Int", [0x10])
this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent.def.ID := New GameObjectStructure(this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent.def.,"Int", [0x10])
this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent.source := New GameObjectStructure(this.OminContractualObligationsHandler.effectKey.parentEffectKeyHandler.parent.,"Int", [0x18])
