; This file was automatically generated by ScriptHubImporter.py
this.SpurtWaspirationHandlerV2.totalStacksNeededForNextEffect := New GameObjectStructure(this.SpurtWaspirationHandlerV2,"Int", [0xa0])
this.SpurtWaspirationHandlerV2.remainingStacksNeededForNextEffect := New GameObjectStructure(this.SpurtWaspirationHandlerV2,"Int", [0xa4])
this.SpurtWaspirationHandlerV2.activeWasps := New GameObjectStructure(this.SpurtWaspirationHandlerV2,"List", [0x98])
this.SpurtWaspirationHandlerV2.effectDatas := New GameObjectStructure(this.SpurtWaspirationHandlerV2,"List", [0x90])
this.SpurtWaspirationHandlerV2.effectDatas.Effect := New GameObjectStructure(this.SpurtWaspirationHandlerV2.effectDatas,"Int", [0x18])
this.SpurtWaspirationHandlerV2.effectDatas.Effect.effectKeyHandlers := New GameObjectStructure(this.SpurtWaspirationHandlerV2.effectDatas.Effect,"List", [0x38])
this.SpurtWaspirationHandlerV2.effectDatas.Effect.effectKeyHandlers.stacks := New GameObjectStructure(this.SpurtWaspirationHandlerV2.effectDatas.Effect.effectKeyHandlers,"Int", [0x90])
this.SpurtWaspirationHandlerV2.effectDatas.Effect.effectKeyHandlers.stacks.stackCount := New GameObjectStructure(this.SpurtWaspirationHandlerV2.effectDatas.Effect.effectKeyHandlers.stacks,"Double", [0x98])
