; This file was automatically generated by ScriptHubImporter.py
this.TimeScaleWhenNotAttackedHandler.scaleActive := New GameObjectStructure(this.TimeScaleWhenNotAttackedHandler,"Char", [0xd8])
this.TimeScaleWhenNotAttackedHandler.effectTime := New GameObjectStructure(this.TimeScaleWhenNotAttackedHandler,"Double", [0xe0])
this.TimeScaleWhenNotAttackedHandler.effectKey := New GameObjectStructure(this.TimeScaleWhenNotAttackedHandler,"Int", [0x18])
this.TimeScaleWhenNotAttackedHandler.effectKey.parentEffectKeyHandler := New GameObjectStructure(this.TimeScaleWhenNotAttackedHandler.effectKey,"Int", [0x8])
this.TimeScaleWhenNotAttackedHandler.effectKey.parentEffectKeyHandler.parent := New GameObjectStructure(this.TimeScaleWhenNotAttackedHandler.effectKey.parentEffectKeyHandler,"Int", [0x8])
this.TimeScaleWhenNotAttackedHandler.effectKey.parentEffectKeyHandler.parent.def := New GameObjectStructure(this.TimeScaleWhenNotAttackedHandler.effectKey.parentEffectKeyHandler.parent,"Int", [0x8])
this.TimeScaleWhenNotAttackedHandler.effectKey.parentEffectKeyHandler.parent.def.ID := New GameObjectStructure(this.TimeScaleWhenNotAttackedHandler.effectKey.parentEffectKeyHandler.parent.def,"Int", [0x8])
this.TimeScaleWhenNotAttackedHandler.effectKey.parentEffectKeyHandler.parent.source := New GameObjectStructure(this.TimeScaleWhenNotAttackedHandler.effectKey.parentEffectKeyHandler.parent,"Int", [0xc])
