; This file was automatically generated by ScriptHubImporter.py
this.NrakkUltimateAttackHandler.maxAttacks := New GameObjectStructure(this.NrakkUltimateAttackHandler,"Int", [0xd8])
this.NrakkUltimateAttackHandler.attacksCounter := New GameObjectStructure(this.NrakkUltimateAttackHandler,"Int", [0x10c])
this.NrakkUltimateAttackHandler.overlay := New GameObjectStructure(this.NrakkUltimateAttackHandler,"Int", [0x90])
this.NrakkUltimateAttackHandler.overlay.lastSetFilledPercent := New GameObjectStructure(this.NrakkUltimateAttackHandler.overlay,"Float", [0x394])
this.NrakkUltimateAttackHandler.overlay.lastSetTargetArcPercent := New GameObjectStructure(this.NrakkUltimateAttackHandler.overlay,"Float", [0x390])
