; This file was automatically generated by ScriptHubImporter.py
this.SpurtWaspirationHandlerV2.activeWasps := New GameObjectStructure(this.SpurtWaspirationHandlerV2,"List", [0xa0])
this.SpurtWaspirationHandlerV2.activeWasps._CollectionValType := "CrusadersGame.Effects.SpurtWaspirationHandlerV2.Wasp"
