; This file was automatically generated by ScriptHubImporter.py
this.BuffDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0x10])
this.AreaDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0xc])
this.UpgradeDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0x6c])
this.AdventureDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0xa0])
this.ChestTypeDefines := New GameObjectStructure(this.CrusadersGame.Defs.CrusadersGameDataSet,"List", [0x20])
this.ChestTypeDefines.ID := New GameObjectStructure(this.ChestTypeDefines,"Int", [0x8])
this.ChestTypeDefines.NamePlural := New GameObjectStructure(this.ChestTypeDefines,"UTF-16", [0x10])
this.ChestTypeDefines.Name := New GameObjectStructure(this.ChestTypeDefines,"UTF-16", [0xc])
