; This file was automatically generated by ScriptHubImporter.py
this.UserID := New GameObjectStructure(this.CrusadersGame.GameSettings,"Int", [this.StaticOffset + 0x20])
this.Hash := New GameObjectStructure(this.CrusadersGame.GameSettings,"UTF-16", [this.StaticOffset + 0x28])
this.Platform := New GameObjectStructure(this.CrusadersGame.GameSettings,"Int", [this.StaticOffset + 0x48])
this.MobileClientVersion := New GameObjectStructure(this.CrusadersGame.GameSettings,"Int", [this.StaticOffset + 0x50])
this.VersionPostFix := New GameObjectStructure(this.CrusadersGame.GameSettings,"UTF-16", [this.StaticOffset + 0x54])
this._instance := New GameObjectStructure(this.CrusadersGame.GameSettings,"Int", [this.StaticOffset + 0x0])
this._instance.instanceID := New GameObjectStructure(this._instance,"Int", [0x10])
