;Automatic generated by Addon Management
#include *i C:\Idle\ICScriptHub\Idle-Champions\AddOns\IC_Addon_Management\IC_Addon_Management_Functions.ahk\..\..\IC_About\IC_About_Component.ahk
#include *i C:\Idle\ICScriptHub\Idle-Champions\AddOns\IC_Addon_Management\IC_Addon_Management_Functions.ahk\..\..\IC_Addon_Management\IC_Addon_Management_Includes.ahk
#include *i C:\Idle\ICScriptHub\Idle-Champions\AddOns\IC_Addon_Management\IC_Addon_Management_Functions.ahk\..\..\IC_BrivGemFarm_Performance\IC_BrivGemFarm_Component.ahk
