;Automatic generated by Addon Management
#include *i C:\Idle\ICScriptHub\Idle-Champions\AddOns\IC_Addon_Management\IC_Addon_Management_Functions.ahk\..\..\IC_About\IC_About_Component.ahk
#include *i C:\Idle\ICScriptHub\Idle-Champions\AddOns\IC_Addon_Management\IC_Addon_Management_Functions.ahk\..\..\IC_Addon_Management\IC_Addon_Management_Includes.ahk
#include *i C:\Idle\ICScriptHub\Idle-Champions\AddOns\IC_Addon_Management\IC_Addon_Management_Functions.ahk\..\..\IC_BrivGemFarm_Performance\IC_BrivGemFarm_Component.ahk
#include *i C:\Idle\ICScriptHub\Idle-Champions\AddOns\IC_Addon_Management\IC_Addon_Management_Functions.ahk\..\..\IC_ChestPurchaser\IC_ChestPurchaser_Component.ahk
#include *i C:\Idle\ICScriptHub\Idle-Champions\AddOns\IC_Addon_Management\IC_Addon_Management_Functions.ahk\..\..\IC_DashCheck\IC_DashCheck_Component.ahk
#include *i C:\Idle\ICScriptHub\Idle-Champions\AddOns\IC_Addon_Management\IC_Addon_Management_Functions.ahk\..\..\IC_GameLocationSettings\IC_GameLocationSettings_Component.ahk
#include *i C:\Idle\ICScriptHub\Idle-Champions\AddOns\IC_Addon_Management\IC_Addon_Management_Functions.ahk\..\..\IC_InventoryView\IC_InventoryView_Component.ahk
#include *i C:\Idle\ICScriptHub\Idle-Champions\AddOns\IC_Addon_Management\IC_Addon_Management_Functions.ahk\..\..\IC_Jimothy\IC_Jimothy_Component.ahk
#include *i C:\Idle\ICScriptHub\Idle-Champions\AddOns\IC_Addon_Management\IC_Addon_Management_Functions.ahk\..\..\IC_MemoryFunctions\IC_MemoryFunctions_Component.ahk
#include *i C:\Idle\ICScriptHub\Idle-Champions\AddOns\IC_Addon_Management\IC_Addon_Management_Functions.ahk\..\..\IC_MemoryFunctionsFullRead\IC_MemoryFunctionsFullRead_Component.ahk
